version: '3.4'

services:
  resolvefrom:
    image: resolvefrom
    build:
      context: node_modules/resolve-from
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
